name: "Bug"
description: "Bug ticket with reproducible steps and expected behaviour"
title: "AAC-XX: Bug - <short title>"
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: "Describe the issue clearly."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence (logs/screenshots)
      description: Paste error logs or attach screenshots if helpful.
